import type { Metadata } from 'next';

import { DotorihamCoreProvider } from '../providers/dotoriham-core-provider';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // TODO: cookie로 color scheme을 가져오는 것을 구현해야 함
  return (
    <html lang="en" data-dotoriham-color-scheme="dark">
      <body suppressHydrationWarning={true}>
        <DotorihamCoreProvider>{children}</DotorihamCoreProvider>
      </body>
    </html>
  );
}
