import type { Metadata } from 'next';
import { DotorihamCoreProvider } from '@/providers/dotoriham-core-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <DotorihamCoreProvider>{children}</DotorihamCoreProvider>
      </body>
    </html>
  );
}
